# Generated by Django 2.1.2 on 2018-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
